version: '3.4'

services: 
  redis:
     image: redis:6.2
     restart: always
     environment:
        REDIS_PASSWORD: redis2022#=
         -REDIS_URL=redis://redis:6379

     ports:
      - "6379:6379"
     healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
     volumes:
       - ./redis.conf:/usr/local/etc/redis/redis.conf
     command: redis-server /usr/local/etc/redis/redis.conf
     networks:
     - redis_demo

networks:
   redis_demo:
     driver: bridge

