version: '3.4'

services:
  redis.cache.api:
    image: ${DOCKER_REGISTRY-}rediscacheapi
    build:
      context: .
      dockerfile: Redis.Cache.API/Dockerfile
    environment: {
            "TZ": "America/Sao_Paulo"
    }




