version: '3.4'

services:
  redis.cache.api:
    image: api:redis
    build:
       context: .
       dockerfile: Redis.Cache.API/Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - REDIS_HOST=redis
      - RedisConnection=redis_cache
    volumes:
      - ~/.aspnet/https:/https:ro    
    restart: always
    depends_on:
      redis:
        condition: service_healthy      
    networks:
     - redis_demo




