version: '3.4'

services:
  redis.cache.api:
    image: api:redis
    build:
       context: .
       dockerfile: Redis.Cache.API/Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro    
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    networks:
     - redis_demo
  

  redis:
     image: redis
     restart: always
     environment:
        REDIS_PASSWORD: redis2022#=
     ports:
      - "6379:6379"
     healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
     networks:
     - redis_demo

networks:
   redis_demo:
     driver: bridge

